image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits@1.10.1:ztHr0xX5hkfQilbTTFitFw==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'